### ISSUE TITLE
running psn container fails

### ISSUE THREAD

**Issue by dpastoor** [osmosisfoundation/pmx-docker#2]
just tried to run the psn container independently to use update_inits on a machine without psn installed

```
docker run --rm -v C:\Users\devin\Documents\Repos\manuscript-vancomycin-bayesian\modeling:/data -it --entrypoint bash osmosisfoundation/psn
```

however from the bash shell get the following error

```
In PsN configuration file[/usr/local/share/perl/5.22.1/PsN_4_6_0/psn.conf]:File '/usr/local/share/perl/5.22.1/PsN_4_6_0/psn.conf' does not exist at /usr/local/share/perl/5.22.1/PsN_4_6_0/PsN.pm line 56.
BEGIN failed--compilation aborted at /usr/bin/update_inits line 6.
```

When trying any other commands or even accessing help the following errors persist.

**Comment by dpastoor** [comment]
Note - this issue is not present in rocker, which I ended up using just to access psn.

**Comment by billdenney** [comment]
The issue appears to be with the expect script.  Expect an update shortly (pun intended).

**Comment by BretFisher** [comment]
Latest commits fix this issue.  See example usage in the updated [README.md](https://github.com/osmosisfoundation/pmx-docker/blob/master/README.md#how-to-use)
