### ISSUE TITLE
NONMEM License Update is Required for Tests

### ISSUE THREAD

**Issue by billdenney** [osmosisfoundation/pmx-docker#3]
My preference is that if the installation isn't tested, the Docker image isn't generated.  That way, my qualification tests are as simple as "If the image exists, it's qualified."  For that, the NONMEM license file must be updated prior to starting the `SETUP` script.

Currently, the NONMEM installation indicates that the license is expired, and no tests are run.

If we add the following lines to the NONMEM Dockerfile, it would update the license file (without requiring a copy operation):

```
# Preamble
ARG NONMEM_LICENSE_STRING=""
# ... just before running SETUP
  && if [ -n "$NONMEM_LICENSE_STRING" ]; then echo $NONMEM_LICENSE_STRING > /opt/nm/license/nonmem.lic ; fi \
# ... run SETUP and the rest of the Dockerfile
```

**Comment by BretFisher** [comment]
Anything in an ARG of a final build image/stage is retrevable via the image layers history, so best not to put sensive info in that. See 1st comment in #4 for a path forward :)

**Comment by billdenney** [comment]
Definitely true.  I was just trying to improve relative to current state more than thinking of this as a long-term fix.  I'm very interested in the multi-stage builds option you suggested in #4.

**Comment by billdenney** [comment]
This is definitely not the best solution for a public image.  I view it as an improved solution until we have the public image solution fixed.

**Comment by BretFisher** [comment]
I feel like this and #4 are same, so will close this issue and we can discuss in #4 to keep the final fix easier to understand/track.
