### ISSUE TITLE
Recent commit breaks image building on Docker Hub

### ISSUE THREAD

**Issue by BretFisher** [osmosisfoundation/pmx-docker#8]
Hey @dpastoor @vjd @billdenney,

Currently, Docker Cloud image builds are broken due to recent commits that merged dockerfiles and other ENV's, see https://github.com/osmosisfoundation/pmx-docker/commit/5ffee727d213fc3eb6c5fb281d5455996a46dd21 and https://github.com/osmosisfoundation/pmx-docker/commit/49f72097df1e5d3bb93fbd0e761400e14f05a650

So let me give some background on why things are were the way they were 😄 

A month or so back when nonmem 7.4 came out, I had two goals for the nonmem dockerfile:

1. provide a way for 7.3 and 7.4 to be supported in docker images, and eventually all future versions we want to support. We'll likely need to offer more then "latest".
2. Have Docker Hub/Cloud auto-build those various images on each github commit.
3. A 3rd goal was given to me by Vijay: to remove passwords from images/repo.

In order to remove passwords and also have auto-builds, the current image building tool (Cloud/Hub) needs to hold the passwords, and also know when to use which passwords (7.3 and 7.4 have different passwords) and give them different image tags for Docker Hub to distinguish.

Due to the limits of Docker Cloud (Cloud is a super-set of features of Hub for CI/CD), the best I could come up with to meet those requirements was a separate, yet redundant Dockerfile for each version. That way Cloud can build each version with it's own environment variable for password and it's own image tags.

To test if changes break builds, you can fork and add the forks to your own Docker Cloud and test building, or maybe test a new branch by [changing settings in cloud here](https://cloud.docker.com/app/osmosisfoundation/repository/docker/osmosisfoundation/nonmem/builds) (Vijay can give or ask me to give access).

We could also move to a more advanced build tool like codeship.com but that would be a larger time investment then the current path.

Happy to discuss these and other options, but the quickest way back to proper image building is to revert those two commits.

**Comment by dpastoor** [comment]
@BretFisher when building, am I correct in thinking that the build command is coming from https://github.com/osmosisfoundation/pmx-docker/blob/master/nonmem/hooks/build

Can we not just apply a little conditional logic at the build script for hub? eg in pseudocode

nmpass = ""
if nm_minor_version == 4 {
   nmpass = $NM_PASSWORD_74
} else if nm_minor_version == 3 {
 nmpass = $NM_PASSWORD_73
} else {
...
}

docker build --buildarg NONMEM_ZIP_PASS=nmpass


I still wonder if the best implementation regardless is to engage ICON and see if we can just mirror the non-password-protected tarballs here, their FTP site is slow and can be unreliable anyway. It would make it easier for people to build locally themselves too.

**Comment by BretFisher** [comment]
Pretty sure I ruled all that out when I had to create that build hook because I didn't like the dupe files, but since the build arguments had to be different for different tags, I wasn't smart enough. Let me take another look.

**Comment by BretFisher** [comment]
For now I'm reverting the previous merge to get builds/solution working again with Hub. We can test various ways to reduce the duplication later, but for now it'll work :)
